### ISSUE TITLE
VS2015+ffmpeg2.+: 生成的.H264文件不能播放

### ISSUE THREAD

**Issue by ailego** [yujie123jw/ffmpegtoh264#1]
使用”ffplay -i test.h264“得到如下结果：
[h264 @ 000000000272cbc0] non-existing PPS 0 referenced
[h264 @ 000000000272cbc0] decode_slice_header error
[h264 @ 000000000272cbc0] no frame!
之前也测试过HJL作者的那个版本，应该是修改自雷霄骅最初的版本，调试完成后生成的h264文件都不能播放。
PS：RTSP地址修改为了rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov，因为demo里的无法链接。

**Comment by yujie123jw** [comment]
你好  你可以直接试一下用 VLC  播放 如果是用其它播放器的话  建议用ffmpege先合成mp4.命令如下：
ffmpeg -i test.h264 -vcodec copy -f mp4 test.mp4  我试过在通用的播放器都可以播放，如再有问题请反映。

**Comment by ailego** [comment]
你好，用VLC无法播放，用ffmpeg转格式无法成功，同样还是报错：
[h264 @ 00000000001e8960] decode_slice_header error
[h264 @ 00000000001e8960] no frame!
[h264 @ 00000000001e8960] non-existing PPS 0 referenced
[h264 @ 00000000001e8960] decode_slice_header error
[h264 @ 00000000001e8960] no frame!
[h264 @ 00000000001e8960] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000000001e8960] decode_slice_header error
[h264 @ 00000000001e8960] no frame!
[h264 @ 00000000001e8960] non-existing PPS 0 referenced
    Last message repeated 2 times
[h264 @ 00000000001e8960] decode_slice_header error
[h264 @ 00000000001e8960] no frame!
[h264 @ 00000000001e6e80] decoding for stream 0 failed
[h264 @ 00000000001e6e80] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, h264, from 'F:\\test.h264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 25 fps, 25 tbr, 1200k tbn, 50 tbc
[mp4 @ 0000000000647620] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
    Last message repeated 1 times

我只是修改了代码中的RTSP测试地址，可是生成的h264文件却应该少了一些关键的识别帧，如果这个问题只有我遇到了，这让我很困惑。

**Comment by yujie123jw** [comment]
上面 显示是 没有 PPS  你看看  你发的源流里面有没有  PPS 用tcpdump  winshark这个的 工具看一下  。 标识应该是 第二 00 00 00 01 后面  ,winshark 应该可以直接看得到 很个很大的PPS.

**Comment by ailego** [comment]
是因为这个，已经解决了。
参考http://blog.csdn.net/leixiaohua1020/article/details/11800877
